// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld.proto

package helloworld

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ListContainer struct {
	// The name of the feature.
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListContainer) Reset()         { *m = ListContainer{} }
func (m *ListContainer) String() string { return proto.CompactTextString(m) }
func (*ListContainer) ProtoMessage()    {}
func (*ListContainer) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{2}
}

func (m *ListContainer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListContainer.Unmarshal(m, b)
}
func (m *ListContainer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListContainer.Marshal(b, m, deterministic)
}
func (m *ListContainer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListContainer.Merge(m, src)
}
func (m *ListContainer) XXX_Size() int {
	return xxx_messageInfo_ListContainer.Size(m)
}
func (m *ListContainer) XXX_DiscardUnknown() {
	xxx_messageInfo_ListContainer.DiscardUnknown(m)
}

var xxx_messageInfo_ListContainer proto.InternalMessageInfo

func (m *ListContainer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ContainerList struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerList) Reset()         { *m = ContainerList{} }
func (m *ContainerList) String() string { return proto.CompactTextString(m) }
func (*ContainerList) ProtoMessage()    {}
func (*ContainerList) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{3}
}

func (m *ContainerList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerList.Unmarshal(m, b)
}
func (m *ContainerList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerList.Marshal(b, m, deterministic)
}
func (m *ContainerList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerList.Merge(m, src)
}
func (m *ContainerList) XXX_Size() int {
	return xxx_messageInfo_ContainerList.Size(m)
}
func (m *ContainerList) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerList.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerList proto.InternalMessageInfo

func (m *ContainerList) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "helloworld.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "helloworld.HelloReply")
	proto.RegisterType((*ListContainer)(nil), "helloworld.ListContainer")
	proto.RegisterType((*ContainerList)(nil), "helloworld.ContainerList")
}

func init() { proto.RegisterFile("helloworld.proto", fileDescriptor_17b8c58d586b62f2) }

var fileDescriptor_17b8c58d586b62f2 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x31, 0x4b, 0xc4, 0x30,
	0x14, 0xc7, 0x2f, 0x20, 0x77, 0xfa, 0xf0, 0x54, 0xde, 0x70, 0xd4, 0x73, 0x91, 0x08, 0xea, 0x14,
	0x44, 0x77, 0x87, 0x73, 0xf0, 0x06, 0x87, 0xa3, 0x0e, 0xce, 0x51, 0x1f, 0xb5, 0x90, 0x36, 0x31,
	0x49, 0xd1, 0x7e, 0x0e, 0xbf, 0xb0, 0x24, 0xb4, 0x9a, 0x40, 0xb7, 0xf7, 0xcf, 0xff, 0x47, 0xf2,
	0xcb, 0x83, 0x93, 0x0f, 0x52, 0x4a, 0x7f, 0x69, 0xab, 0xde, 0x85, 0xb1, 0xda, 0x6b, 0x84, 0xff,
	0x13, 0xce, 0xe1, 0x70, 0x1b, 0x52, 0x49, 0x9f, 0x1d, 0x39, 0x8f, 0x08, 0x7b, 0xad, 0x6c, 0xa8,
	0x60, 0xe7, 0xec, 0xfa, 0xa0, 0x8c, 0x33, 0xbf, 0x04, 0x18, 0x18, 0xa3, 0x7a, 0x2c, 0x60, 0xd1,
	0x90, 0x73, 0xb2, 0x1a, 0xa1, 0x31, 0xf2, 0x0b, 0x58, 0x3e, 0xd5, 0xce, 0x3f, 0xe8, 0xd6, 0xcb,
	0xba, 0x25, 0x3b, 0x79, 0xd9, 0x15, 0x2c, 0xff, 0x80, 0x40, 0xe3, 0x0a, 0xe6, 0x96, 0x5c, 0xa7,
	0xfc, 0x80, 0x0d, 0xe9, 0xf6, 0x87, 0xc1, 0xe2, 0xd1, 0x12, 0x79, 0xb2, 0x78, 0x0f, 0xfb, 0xcf,
	0xb2, 0x8f, 0x12, 0x58, 0x88, 0xe4, 0x43, 0xa9, 0xfb, 0x7a, 0x35, 0xd1, 0x18, 0xd5, 0xf3, 0x19,
	0x6e, 0xe1, 0x28, 0x33, 0x73, 0x78, 0x9a, 0xb2, 0x59, 0xb7, 0xce, 0xaa, 0xcc, 0x95, 0xcf, 0x36,
	0x37, 0x70, 0x56, 0x6b, 0x51, 0x59, 0xf3, 0x26, 0xe8, 0x5b, 0x36, 0x46, 0x91, 0x4b, 0xf0, 0xcd,
	0x71, 0x7c, 0xf6, 0x25, 0xcc, 0xbb, 0xb0, 0xeb, 0x1d, 0x7b, 0x9d, 0xc7, 0xa5, 0xdf, 0xfd, 0x06,
	0x00, 0x00, 0xff, 0xff, 0x01, 0xee, 0x5f, 0x91, 0x88, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	ListContainers(ctx context.Context, in *ListContainer, opts ...grpc.CallOption) (*ContainerList, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) ListContainers(ctx context.Context, in *ListContainer, opts ...grpc.CallOption) (*ContainerList, error) {
	out := new(ContainerList)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/ListContainers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	ListContainers(context.Context, *ListContainer) (*ContainerList, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_ListContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContainer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).ListContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/ListContainers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).ListContainers(ctx, req.(*ListContainer))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
		{
			MethodName: "ListContainers",
			Handler:    _Greeter_ListContainers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld.proto",
}
